name: Build Docker Image

on:
  push:

  tags: ['v*.*.*']
  workflow_dispatch:

  env:
   REGISTRY:  ghcr.io
   IMAGE_NAME :   ${{github.repository}} 

   jobs:
      build:

      runs-on:ubuntu-latest
      permissions:
      content: read
      packages: write



  steps:
  - name: Checkout Repository
  uses: actions/checkout@v3



   - name: set up NODEJS
   uses: actions/setupNodeJS
   with:
     node-version:  '16'
     distribution: 'adopt'

    - name: Setup Docker buildx
    uses: docker/setup-buildx-action@v2.0.0



    - name: log into registry 
    if: github.event_name != 'pull_request'
    uses: docker/login-action@v2.0.0
    with:
    registry :  ${{env.REGISTRY}} 
    username :  ${{env.REGISTRY}} { %endraw %}     
    password:  {% raw %} ${{secrest.GITHUB_TOKEN}} {% endraw %}



  - name : Extract docker metadata
  id:meta
  uses: docker/metadata-action@4.0.1
  with:
  images: {% raw %} ${{env.REGISTRY}} / %{{env.IMAGE_NAME}}  {% endraw %}

  - name: Build and push Docker image
  id: build-and-push
  uses: docker/build-push-action@v3.0.0
  
  with:
  context:
  push: